### ISSUE TITLE
连接 Netlify

### ISSUE THREAD

**Issue by yihui** [HuaiyuZhang/rnorm.org#1]
用 Github 登录 https://app.netlify.com 创建一个新站点，连这个库，设置用 `hugo_0.18` 编译，发布文件夹为 `public`，看起来大致如下：

![image](https://cloud.githubusercontent.com/assets/163582/24436530/a5064566-1401-11e7-9518-cc7f5d194768.png)

然后用我的邮箱地址`xie@yihui.name`分配给我访问权限（Access）。

Netlify 是一个云端编译网站的公司，提供的编译工具包括 Hugo，挺好用的。

**Comment by HuaiyuZhang** [comment]
完成

**Comment by yihui** [comment]
完美
